"""add stat

Revision ID: 6d055c59b60a
Revises: ce62c0f0e958
Create Date: 2025-11-14 19:41:41.559264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d055c59b60a'
down_revision: Union[str, Sequence[str], None] = 'ce62c0f0e958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_item', sa.String(length=64), nullable=False),
    sa.Column('menu_task', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_chat_id'), 'statistics', ['chat_id'], unique=False)
    op.create_index('ix_statistics_city_created', 'statistics', ['city_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_statistics_city_id'), 'statistics', ['city_id'], unique=False)
    op.create_index(op.f('ix_statistics_created_at'), 'statistics', ['created_at'], unique=False)
    op.create_index('ix_statistics_key', 'statistics', ['key'], unique=False)
    op.create_index('ix_statistics_menu_item_task', 'statistics', ['menu_item', 'menu_task'], unique=False)
    op.create_index('ix_statistics_user_created', 'statistics', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_statistics_user_id'), 'statistics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_user_id'), table_name='statistics')
    op.drop_index('ix_statistics_user_created', table_name='statistics')
    op.drop_index('ix_statistics_menu_item_task', table_name='statistics')
    op.drop_index('ix_statistics_key', table_name='statistics')
    op.drop_index(op.f('ix_statistics_created_at'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_city_id'), table_name='statistics')
    op.drop_index('ix_statistics_city_created', table_name='statistics')
    op.drop_index(op.f('ix_statistics_chat_id'), table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
