"""add next_sub to invoice

Revision ID: 8de97d7d4182
Revises: efd793009193
Create Date: 2025-11-07 11:45:51.247250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de97d7d4182'
down_revision: Union[str, Sequence[str], None] = 'efd793009193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('next_sub', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'next_sub')
    # ### end Alembic commands ###
