"""init

Revision ID: 980c3d9ca95e
Revises: 
Create Date: 2025-11-04 16:38:18.842827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980c3d9ca95e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_pl', sa.String(length=128), nullable=False),
    sa.Column('name_uk', sa.String(length=128), nullable=True),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_pl')
    )
    op.create_index('ix_cities_name_pl', 'cities', ['name_pl'], unique=False)
    op.create_table('fsm_states',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('subscription_until', sa.DateTime(timezone=True), nullable=True, comment='Дата и время окончания подписки пользователя (UTC)'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_last_active_at', 'users', ['last_active_at'], unique=False)
    op.create_index('ix_users_registered_at', 'users', ['registered_at'], unique=False)
    op.create_index(op.f('ix_users_subscription_until'), 'users', ['subscription_until'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('name_pl', sa.String(length=128), nullable=False),
    sa.Column('name_uk', sa.String(length=128), nullable=True),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'name_pl', name='uq_district_city_namepl')
    )
    op.create_index('ix_districts_city', 'districts', ['city_id'], unique=False)
    op.create_index('ix_districts_name_pl', 'districts', ['name_pl'], unique=False)
    op.create_table('scheduled_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_type', sa.Enum('PRIVATE', 'CHANNEL', name='chat_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('message_type', sa.Enum('REMINDER', 'BROADCAST', 'CUSTOM', 'INVOICE', name='message_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CLAIMED', 'SENDING', 'SENT', 'FAILED', 'CANCELED', name='scheduled_status', native_enum=False, create_constraint=True), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('idempotent', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sched_chat', 'scheduled_messages', ['chat_id'], unique=False)
    op.create_index('ix_sched_status_sendat_prio', 'scheduled_messages', ['status', 'send_at', 'priority'], unique=False)
    op.create_index('ix_sched_user', 'scheduled_messages', ['user_id'], unique=False)
    op.create_index('uq_sched_dedup_key_not_null', 'scheduled_messages', ['dedup_key'], unique=True, postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.create_table('user_card_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_card_tokens_user_active', 'user_card_tokens', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_card_tokens_user_id'), 'user_card_tokens', ['user_id'], unique=False)
    op.create_table('user_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('deal_type', sa.String(length=16), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('area_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rooms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('child_allowed', sa.Boolean(), nullable=True),
    sa.Column('no_comission', sa.Boolean(), nullable=True),
    sa.Column('has_confirmed_policy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_search_city', 'user_searches', ['city_id'], unique=False)
    op.create_index('ix_user_search_user_id', 'user_searches', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('invoice_type', sa.Enum('SUBSCRIPTION', 'ONE_TIME', name='invoice_type'), nullable=False),
    sa.Column('subscribe_type', sa.String(length=64), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payu_order_id', sa.String(length=64), nullable=True),
    sa.Column('payu_ext_order_id', sa.String(length=64), nullable=True),
    sa.Column('payu_payment_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'WAITING_FOR_CONFIRMATION', 'COMPLETED', 'CANCELED', 'REJECTED', name='invoice_status'), nullable=False),
    sa.Column('card_token_id', sa.Integer(), nullable=True),
    sa.Column('payu_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_refunded', sa.Boolean(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_token_id'], ['user_card_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_payu_ext_order_id'), 'invoices', ['payu_ext_order_id'], unique=True)
    op.create_index(op.f('ix_invoices_payu_order_id'), 'invoices', ['payu_order_id'], unique=True)
    op.create_index(op.f('ix_invoices_payu_payment_id'), 'invoices', ['payu_payment_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_index('ix_invoices_user_status', 'invoices', ['user_id', 'status'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ad_id', sa.String(length=128), nullable=False),
    sa.Column('property_type', sa.String(length=16), nullable=False),
    sa.Column('deal_type', sa.String(length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_hash', sa.String(length=32), sa.Computed('md5(description)', persisted=True), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('title_uk', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_uk', sa.Text(), nullable=True),
    sa.Column('is_translated', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('child_allowed', sa.Boolean(), nullable=True),
    sa.Column('no_comission', sa.Boolean(), nullable=True),
    sa.Column('is_sended', sa.Boolean(), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tg_photo_id', sa.String(length=256), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_check', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("deal_type IN ('rent','sale')", name='ck_deal_type'),
    sa.CheckConstraint("property_type IN ('apartment','house','room')", name='ck_property_type'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_ad_id', name='uq_source_ad')
    )
    op.create_index('ix_listings_city', 'listings', ['city_id'], unique=False)
    op.create_index('ix_listings_city_deal', 'listings', ['city_id', 'deal_type'], unique=False)
    op.create_index('ix_listings_city_prop_deal_desc_hash', 'listings', ['city_id', 'property_type', 'deal_type', 'description_hash'], unique=False)
    op.create_index(op.f('ix_listings_description_hash'), 'listings', ['description_hash'], unique=False)
    op.create_index(op.f('ix_listings_last_check'), 'listings', ['last_check'], unique=False)
    op.create_index('ix_listings_price', 'listings', ['price'], unique=False)
    op.create_index('ix_listings_property_type', 'listings', ['property_type'], unique=False)
    op.create_table('user_search_districts',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['user_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id', 'district_id')
    )
    op.create_table('saved_listings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_saved_user_listing')
    )
    op.create_index(op.f('ix_saved_listings_created_at'), 'saved_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_listings_listing_id'), 'saved_listings', ['listing_id'], unique=False)
    op.create_index('ix_saved_listings_user_created', 'saved_listings', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_saved_listings_user_id'), 'saved_listings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_listings_user_id'), table_name='saved_listings')
    op.drop_index('ix_saved_listings_user_created', table_name='saved_listings')
    op.drop_index(op.f('ix_saved_listings_listing_id'), table_name='saved_listings')
    op.drop_index(op.f('ix_saved_listings_created_at'), table_name='saved_listings')
    op.drop_table('saved_listings')
    op.drop_table('user_search_districts')
    op.drop_index('ix_listings_property_type', table_name='listings')
    op.drop_index('ix_listings_price', table_name='listings')
    op.drop_index(op.f('ix_listings_last_check'), table_name='listings')
    op.drop_index(op.f('ix_listings_description_hash'), table_name='listings')
    op.drop_index('ix_listings_city_prop_deal_desc_hash', table_name='listings')
    op.drop_index('ix_listings_city_deal', table_name='listings')
    op.drop_index('ix_listings_city', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_invoices_user_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payu_payment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payu_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payu_ext_order_id'), table_name='invoices')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_user_search_user_id', table_name='user_searches')
    op.drop_index('ix_user_search_city', table_name='user_searches')
    op.drop_table('user_searches')
    op.drop_index(op.f('ix_user_card_tokens_user_id'), table_name='user_card_tokens')
    op.drop_index('ix_card_tokens_user_active', table_name='user_card_tokens')
    op.drop_table('user_card_tokens')
    op.drop_index('uq_sched_dedup_key_not_null', table_name='scheduled_messages', postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.drop_index('ix_sched_user', table_name='scheduled_messages')
    op.drop_index('ix_sched_status_sendat_prio', table_name='scheduled_messages')
    op.drop_index('ix_sched_chat', table_name='scheduled_messages')
    op.drop_table('scheduled_messages')
    op.drop_index('ix_districts_name_pl', table_name='districts')
    op.drop_index('ix_districts_city', table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_users_subscription_until'), table_name='users')
    op.drop_index('ix_users_registered_at', table_name='users')
    op.drop_index('ix_users_last_active_at', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_table('fsm_states')
    op.drop_index('ix_cities_name_pl', table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
