"""init listings

Revision ID: 98c5b8fd2fc7
Revises: 
Create Date: 2025-09-24 11:07:26.791640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98c5b8fd2fc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('deal_type', sa.String(length=8), nullable=False),
    sa.Column('property_type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('area_total_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_living_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_kitchen_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floors_total', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.CheckConstraint("deal_type IN ('rent','sale')", name='ck_deal_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external'),
    sa.UniqueConstraint('url', name='uq_url')
    )
    op.create_index('ix_listings_city_deal', 'listings', ['city', 'deal_type'], unique=False)
    op.create_index('ix_listings_fingerprint', 'listings', ['fingerprint'], unique=False)
    op.create_index('ix_listings_source_external', 'listings', ['source', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listings_source_external', table_name='listings')
    op.drop_index('ix_listings_fingerprint', table_name='listings')
    op.drop_index('ix_listings_city_deal', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
