"""add full and paid

Revision ID: ce62c0f0e958
Revises: 8de97d7d4182
Create Date: 2025-11-08 10:28:13.542672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce62c0f0e958'
down_revision: Union[str, Sequence[str], None] = '8de97d7d4182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_full_sub', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_paid')
    op.drop_column('users', 'is_full_sub')
    # ### end Alembic commands ###
