"""add refferal balance

Revision ID: efd793009193
Revises: d3985fb4f3e9
Create Date: 2025-11-07 08:51:15.031996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd793009193'
down_revision: Union[str, Sequence[str], None] = 'd3985fb4f3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_balance_current', sa.Numeric(precision=14, scale=2, asdecimal=False), server_default=sa.text('0'), nullable=False, comment='Текущий доступный реферальный баланс (валюта по договорённости)'))
    op.add_column('users', sa.Column('referral_earnings_total', sa.Numeric(precision=14, scale=2, asdecimal=False), server_default=sa.text('0'), nullable=False, comment='Суммарно начислено по реферальной программе за всё время'))
    op.create_index('ix_users_referral_balance_current', 'users', ['referral_balance_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_referral_balance_current', table_name='users')
    op.drop_column('users', 'referral_earnings_total')
    op.drop_column('users', 'referral_balance_current')
    # ### end Alembic commands ###
